apiVersion: v1
kind: PersistentVolumeClaim
metadata: 
  name: {{ template "smartthings.name" . }}
  namespace: {{ .Values.general.namespace }}
  labels: 
    app: {{ template "smartthings.name" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: {{ .Release.Name | quote }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi