apiVersion: v1
kind: Service
metadata: 
  name: {{ template "smartthings.name" . }}
  namespace: {{ .Values.general.namespace }}
  labels: 
    app: {{ template "smartthings.name" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: {{ .Release.Name | quote }}
spec:
  type: {{ .Values.inbound.type }}
  {{- if .Values.inbound.loadBalancerIP }}
  loadBalancerIP: {{ .Values.inbound.loadBalancerIP }}
  {{- end }}
  selector: 
    app: {{ template "smartthings.name" . }}
    release: {{ .Release.Name }}
  ports: 
    - name: inb
      port: {{ .Values.inbound.port }}
      targetPort: inb