language: generic
sudo: false
branches:
  only:
    - master
env:
  global:
    - HELM_VERSION="v2.9.1"
install:
  - wget http://storage.googleapis.com/kubernetes-helm/helm-${HELM_VERSION}-linux-amd64.tar.gz -O /tmp/helm.tar.gz
  - tar xzf /tmp/helm.tar.gz -C /tmp --strip-components=1
  - chmod +x /tmp/helm
before_script:
  - /tmp/helm init --client-only

script:
  - |
    for chart in *; do
      if [ -d ${chart}]; then
        helm package ${chart}
      fi;
    done;
  - mkdir -p /tmp/charts
  - mv ./*.tgz /tmp/charts
#  - git checkout gh-pages
#  - rm -f *.tgz
#  - rm -f index.yaml
#  - mv /tmp/charts/*.tgz .
#  - helm repo index . --url https://apps.go-home.io
#  - git config user.name "Travis CI"
#  - git config user.email "$COMMIT_AUTHOR_EMAIL"
#  - git add -A .
#  - git commit -m "Deploy to go-home apps: ${SHA}"