apiVersion: v1
kind: Service
metadata: 
  name: {{ template "heketi.name" . }}
  namespace: {{ .Values.general.namespace }}
  labels: 
    app: {{ template "heketi.name" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: {{ .Release.Name | quote }}
spec:
  type: ClusterIP
  selector: 
    app: {{ template "heketi.name" . }}
    release: {{ .Release.Name }}
  ports: 
    - port: 80
      targetPort: http
      name: http