apiVersion: v1
kind: Secret
metadata: 
  name: {{ template "influxdb.name" . }}
  namespace: {{ .Values.general.namespace }}
  labels: 
    app: {{ template "influxdb.name" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: {{ .Release.Name | quote }}
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-delete-policy": hook-failed
data: 
  {{- if .Values.user.login  }}
  influxdb-user: {{ .Values.user.login | b64enc | quote }}
  {{- else }}
  influxdb-user: {{ "gohome" | b64enc | quote }}
  {{- end }}
  {{- if .Values.user.password }}
  influxdb-password: {{ .Values.user.password | b64enc | quote }}
  {{- else }}
  influxdb-password: {{ randAlphaNum 10 | b64enc | quote }}
  {{- end }}
  influxdb-admin: {{ "gohomeadmin" | b64enc | quote }}
  influxdb-admin-password: {{ randAlphaNum 10 | b64enc | quote }}