apiVersion: v1
kind: Service
metadata: 
  name: {{ template "nsqd.name" . }}
  namespace: {{ .Values.general.namespace }}
  labels: 
    app: {{ template "nsqd.name" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: {{ .Release.Name | quote }}
spec:
  type: ClusterIP
  selector: 
    app: {{ template "nsqd.name" . }}
    release: {{ .Release.Name }}
  ports: 
    - name: http
      port: {{ .Values.inbound.http }}
      targetPort: http
    - name: tcp
      port: {{ .Values.inbound.tcp }}
      targetPort: tcp