apiVersion: extensions/v1beta1
kind: Deployment
metadata: 
  name: {{ template "go-home.master.name" . }}
  namespace: {{ .Values.general.namespace }}
  labels: 
    app: {{ template "go-home.master.name" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: {{ .Release.Name | quote }}
spec: 
  replicas: 1
  template:
    metadata: 
      labels:
        app: {{ template "go-home.master.name" . }}
        release: {{ .Release.Name }}
    spec: 
{{- if .Values.general.rbacEnabled }}
      serviceAccountName: {{ template "go-home.name" . }}
{{- end }}
      volumes: 
        - name: plugins
          persistentVolumeClaim:
            claimName: {{ template "go-home.name" . }}
      containers: 
        - name: {{ template "go-home.master.name" . }}
          image: {{ .Values.docker.image }}:{{ .Values.docker.tag }}
          imagePullPolicy: {{ .Values.docker.pullPolicy }}
          resources: 
            requests: 
              cpu: {{ .Values.resources.cpu.requests | quote }}
              memory: {{ .Values.resources.memory.requests | quote }}
            limits: 
              cpu: {{ .Values.resources.cpu.limits | quote }}
              memory: {{ .Values.resources.memory.limits | quote }}
          ports:
            - name: http
              containerPort: {{ .Values.inbound.master }}
              hostPort: {{ .Values.inbound.master }}
              protocol: TCP
          volumeMounts: 
            - name: plugins
              mountPath: /plugins
          command: 
            - /bin/sh
          args:
            - "-c"
            - |
              /go-home/go-home \
              -c provider:k8s \
              -c config-map:{{ .Values.general.namespace }}/{{ .Values.general.masterConfigMap }} \
              -s provider:k8s \
              -s secret:{{ .Values.general.namespace }}/{{ template "go-home.name" . }} \
              --plugins=/plugins