{{- if .Values.general.rbacEnabled }}

kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata: 
  name: {{ template "go-home.name" . }}
  namespace: {{ .Values.general.namespace }}
  labels: 
    app: {{ template "go-home.name" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: {{ .Release.Name | quote }}
rules:
- apiGroups: [""] 
  resources: ["secrets"]
  resourceNames:  [ {{ template "go-home.name" . }} ]
  verbs:
    - "get"
    - "update"
- apiGroups: [""] 
  resources: ["configmaps"]
  resourceNames: 
    - {{ template "go-home.worker.static.name" . }}
    - {{ template "go-home.worker.name" . }}
    - {{ .Values.general.masterConfigMap }}
  verbs:
    - "get"
    - "update"

{{- end}}