apiVersion: v1
kind: Secret
metadata: 
  name: {{ template "go-home.name" . }}
  namespace: {{ .Values.general.namespace }}
  labels: 
    app: {{ template "go-home.name" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: {{ .Release.Name | quote }}
type: Opaque
data: 
  {{- range $key, $val := .Values.users }}
  {{ $key }}: {{ $val }}
  {{- end }}