apiVersion: v1
kind: ConfigMap
metadata: 
  name: {{ template "go-home.worker.static.name" . }}
  namespace: {{ .Values.general.namespace }}
  labels: 
    app: {{ template "go-home.worker.static.name" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: {{ .Release.Name | quote }}
data: 
{{- $root := .Values }}
{{- range $index, $worker := .Values.static }}
  config-{{ $index }}.yaml: |-
    system: go-home
    provider: worker
    name: worker-static-{{ $index }}
    properties:
    {{- range $key, $val := $worker.properties }}
      {{ $key }}: {{ $val }}
    {{- end }}

    {{- if $root.serviceBusConfig }}
    ---
    {{ toYaml $root.serviceBusConfig | trimSuffix "\n" | nindent 4 }}
    {{- end }}

    {{- if $root.loggerConfig  }}
    ---
    {{ toYaml $root.loggerConfig | trimSuffix "\n" | nindent 4 }}
    {{- end }}

{{- end }}