apiVersion: v1
kind: Service
metadata: 
  name: {{ template "chrome.name" . }}
  namespace: {{ .Values.general.namespace }}
  labels: 
    app: {{ template "chrome.name" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: {{ .Release.Name | quote }}
spec:
  type: ClusterIP
  selector: 
    app: {{ template "chrome.name" . }}
    release: {{ .Release.Name }}
  ports: 
    - port: 9222
      targetPort: debug-rc
      name: debug-rc