general: 
  rbacEnabled: true
  namespace: default
  workerReplicas: 2
  masterConfigMap: go-home

docker: 
  image: gohomeio/server
  tag: 0.0.11
  pullPolicy: IfNotPresent

resources: 
  cpu: 
    requests: 120m
    limits: 130m
  memory: 
    requests: 60Mi
    limits: 120Mi

inbound: 
  http: 8080

serviceBusConfig: {}
loggerConfig: {}
workersProperties: {}
users: {}

static: 
  - nodeSelector:
      static: true
    mountDevices: false
    properties: {}
    # will be exposed as host port
    ports: 
      - 5000
    service:
      enabled: true
      type: LoadBalancer
      loadBalancerIP:

bintrayProxy: 
  enabled: false
  url:

inbound:
  master: 8000
  host: ""
  ingressAnnotations: 
    kubernetes.io/ingress.class: traefik
    traefik.ingress.kubernetes.io/redirect-entry-point: https
    traefik.ingress.kubernetes.io/redirect-permanent: true