nameOverride: ""

general: 
  namespace: default
  nodeSelector:

opensky:
  lat:
  lon:
  alt:
  serial: "-serial"
  user:

docker: 
  image: gohomeio/opensky
  tag: 1.0.0
  pullPolicy: IfNotPresent

resources: 
  cpu: 
    requests: 200m
    limits: 400m
  memory: 
    requests: 100Mi
    limits: 200Mi

inbound: 
  enabled: false
  host:
  ingressAnnotations: 
    kubernetes.io/ingress.class: traefik
    ingress.kubernetes.io/auth-type: "basic"
    ingress.kubernetes.io/auth-secret: "k8s-auth"
    traefik.ingress.kubernetes.io/redirect-entry-point: https
    traefik.ingress.kubernetes.io/redirect-permanent: true