apiVersion: extensions/v1beta1
kind: Deployment
metadata: 
  name: {{ template "proxy.name" . }}
  namespace: {{ .Values.general.namespace }}
  labels: 
    app: {{ template "proxy.name" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: {{ .Release.Name | quote }}
spec: 
  replicas: 1
  template:
    metadata: 
      labels:
        app: {{ template "proxy.name" . }}
        release: {{ .Release.Name }}
    spec: 
      volumes: 
        - name: plugins
          persistentVolumeClaim: 
            claimName: {{ .Values.sharedStorage }}
      containers: 
        - name: {{ template "proxy.name" . }}
          image: {{ .Values.docker.image }}:{{ .Values.docker.tag }}
          imagePullPolicy: {{ .Values.docker.pullPolicy }}
          resources: 
            requests: 
              cpu: {{ .Values.resources.cpu.requests | quote }}
              memory: {{ .Values.resources.memory.requests | quote }}
            limits: 
              cpu: {{ .Values.resources.cpu.limits | quote }}
              memory: {{ .Values.resources.memory.limits | quote }}
          ports: 
            - name: http
              containerPort: 9090
              protocol: TCP
          livenessProbe:
            tcpSocket:
              port: http
            initialDelaySeconds: 30
            timeoutSeconds: 5
          readinessProbe:
            tcpSocket:
              port: http
            initialDelaySeconds: 5
            timeoutSeconds: 2
          volumeMounts:
            - name: plugins
              mountPath: /plugins