{{- if .Values.inbound.enabled }}

apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ template "opensky.name" . }}
  namespace: {{ .Values.general.namespace }}
  labels: 
    app: {{ template "opensky.name" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: {{ .Release.Name | quote }}
  annotations:
    {{- range $key, $val := .Values.inbound.ingressAnnotations }}
    {{ $key }}: {{ $val | quote }}
    {{- end }}
spec: 
  rules: 
    - http: 
        paths: 
          - backend: 
              serviceName: {{ template "opensky.name" . }}
              servicePort: 80
      {{- if .Values.inbound.host }}
      host: {{ .Values.inbound.host }}
      {{- end }}

{{- end }}