nameOverride: ""

general: 
  namespace: default
  storageSize: 2Gi

db: 
  name: gohome

inbound: 
  port: 8086
  type: ClusterIP

docker: 
  isArm: true
  imageAmd: "influxdb:1.7.7-alpine"
  imageArm: "arm32v7/influxdb:1.7.7"
  pullPolicy: IfNotPresent

user: 
  login: ""
  password: ""

resources: 
  cpu: 
    requests: 200m
    limits: 400m
  memory: 
    requests: 256Mi
    limits: 512Mi