nameOverride: ""

general: 
  namespace: default

docker: 
  image: gohomeio/nsq
  tag: 1.1.0
  pullPolicy: IfNotPresent

resources: 
  cpu: 
    requests: 300m
    limits: 400m
  memory: 
    requests: 100Mi
    limits: 200Mi

inbound: 
  clusterNS: cluster.local
  tcp: 4150
  http: 4151