general: 
  namespace: default

docker: 
  image: gohomeio/nsq
  tag: 1.0.0
  pullPolicy: IfNotPresent

resources: 
  cpu: 
    requests: 100m
    limits: 100m
  memory: 
    requests: 20Mi
    limits: 30Mi

inbound: 
  clusterNS: cluster.local
  tcp: 4150
  http: 4151